source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.4'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.7'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development


# A library for generating fake data such as names, addresses, and phone numbers.
gem 'faker'

# Flexible authentication solution for Rails with Warden.
gem 'devise'
gem 'devise-i18n'

# Minimal authorization through OO design and pure Ruby classes
gem 'pundit'

# Object-based searching 
gem 'ransack'

# A very fast & simple Ruby web server
gem 'thin'

# Autoprefixer for Ruby and Ruby on Rails 
gem "autoprefixer-rails"

# gem 'will_paginate', '~> 3.1.0'

# bcrypt-ruby is a Ruby binding for the OpenBSD bcrypt() 
gem 'bcrypt-ruby'

# Catches mail and serves it through a dream.
# gem 'mailcatcher'

# Rack-based asset packaging system
gem 'sprockets'

# A Rails engine that helps you put together a super-flexible admin dashboard.
gem "administrate"
# gem "administrate", :git => "git@github.com:souzaleandror/administrate.git"
# gem "administrate", :git => "https://github.com/souzaleandror/administrate.git"

# Plugin that adds search capabilities to belongs_to associations for Administrate
gem 'administrate-field-belongs_to_search'

# FriendlyId is the “Swiss Army bulldozer” of slugging and permalink plugins for ActiveRecord
gem 'friendly_id'

# Rails Plugin that tracks impressions and page views
gem 'impressionist'

# Dynamic nested forms using jQuery made easy; works with formtastic, simple_form or default forms http://github.com/nathanvda/cocoon
gem "cocoon"

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
    # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '~> 2.13'
  gem 'selenium-webdriver'
  gem 'rspec-rails','~> 3.0'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'better_errors'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# group :production do
#   gem 'rails_12factor'
#   gem 'unicorn'
#   # Use CoffeeScript for .coffee assets and views
#   gem 'coffee-rails', '~> 4.1.0'
# end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

ruby "2.4.0"